baseURL = 'http://fahazavana.github.io/'
title = 'Jean Lucien Randrianantenaina'


[languages]
  [languages.en]
    disabled = false
    languageName = 'English'
    languageCode = 'en-gb'
    weight = 1
  
  [languages.fr]
      disabled = true
      languageName = 'French'
      languageCode = 'fr-FR'
      weight = 2
  
  [languages.mg]
    disabled = true
    languageName = 'Malagasy'
    languageCode = 'mg-mg'
    weight = 3


############################# Site Map ##############################
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1



############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Educations"
URL = "#educations"
weight = 3

[[menu.main]]
name = "Publications"
URL = "#publications"
weight = 4

[[menu.main]]
name = "Skills"
URL = "#skills"
weight = 5

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 6


[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 7


#################### default parameters ################################
[params]
    logo_light = "images/favicon_io/android-chrome-192x192.png"
    logo_dark = "images/favicon_io/android-chrome-192x192.png"
    copyright = "Jean Lucien Randrianantenaina &copy;"

    # Meta data
    description = "Personal Portfolio"
    author = "Jean Lucien Randrianantenaina"
    favicon = "images/favicon_io/android-chrome-192x192.png"
    google_analytics = "GTM-WFHLNFTN"

# google-site-ver
[params.googleSiteVerification]
  name = "google-site-verification"
  content = "aUm25JeP5P0ARrayqp0nUugz1QnRRJ-GGQeCbpb26_Q"

# Preloader
[params.preloader]
    enable = true
    preloader = "images/preloader.gif" 

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/Fahazavana"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://mg.linkedin.com/in/randrianantenaina-jean-lucien-82b98622b"

[[params.social]]
icon = "fab fa-x-twitter"
link="https://twitter.com/rjlucienaina"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:rjlucienaina@gmail.com"

  
